---
# Codacy configuration
# Documentation: https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - "*.py"
  - "**/*.py"
  - "backup/**"
  - "gin/postman/**"
  - "gin/*.py"
  - "backup/export_to_sql.py"
  - "gin/postman/generate_uat.py"
  - "gin/jwt_forge_validation.py"

languages:
  python:
    exclude_paths:
      - "*.py"
      - "**/*.py"
      - "backup/**"
      - "gin/postman/**"
      - "gin/*.py"
      - "backup/export_to_sql.py"
      - "gin/postman/generate_uat.py"
      - "gin/jwt_forge_validation.py"

engines:
  bandit:
    enabled: false
  prospector:
    enabled: false
  pylint:
    enabled: false
  flake8:
    enabled: false
  ruff:
    enabled: false
  semgrep:
    exclude_paths:
      - "*.py"
      - "**/*.py"
  duplication:
    exclude_paths:
      - "*.py"
      - "**/*.py"
  revive:
    enabled: true
    exclude_paths:
      - "*.py"
      - "**/*.py"
