import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

// Automatically claim clients (pages) to control them immediately
self.skipWaiting()
clientsClaim()

// Clean up old caches from previous versions
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Add your custom Workbox routing and caching logic here:
// import { registerRoute } from 'workbox-routing'
// import { StaleWhileRevalidate } from 'workbox-strategies'
// 
// registerRoute(
//   ({ request }) => request.destination === 'image',
//   new StaleWhileRevalidate({
//     cacheName: 'images',
//   })
// )
